version: "3.8"
services:

  library_db:
    image: postgres:14.1-alpine
    restart: always
    ports:
      - "5434:5432"
    networks:
      - network-test
    hostname: library_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=library_db
    volumes:
      - ./data.sql