
CREATE TABLE IF NOT EXISTS readers(id SERIAL PRIMARY KEY, name VARCHAR(250), surname VARCHAR(250), email VARCHAR(200));
CREATE TABLE IF NOT EXISTS books(id SERIAL, title VARCHAR(250), author VARCHAR(250), available BOOLEAN, reader_id INTEGER, rent_date DATE NOT NULL DEFAULT CURRENT_DATE, PRIMARY KEY (id), CONSTRAINT fk_reader FOREIGN KEY (reader_id) REFERENCES readers(id));